export const mockStores = [
  {
    id: "SL-44920",
    name: "Green Leaf Market",
    location: "Seattle, WA",
    owner: "Elena Rodriguez",
    status: "active",
    role: "Nhà hàng",
    province: "Washington",
    totalDishes: 128,
    annualRevenue: "1.25 tỷ VND",
    ownerEmail: "elena.rodriguez@email.com",
    ownerPhone: "(206) 555-0123",
    ownerAddress: "456 Green St, Seattle, WA 98101",
    createdAt: "15/05/2023",
  },
  {
    id: "SL-58122",
    name: "Urban Harvest Co.",
    location: "Portland, OR",
    owner: "Marcus Thorne",
    status: "warning",
    role: "Khách sạn",
    province: "Oregon",
    totalDishes: 75,
    annualRevenue: "850 triệu VND",
    ownerEmail: "marcus.thorne@email.com",
    ownerPhone: "(503) 555-0456",
    ownerAddress: "789 Harvest Ave, Portland, OR 97201",
    createdAt: "22/08/2023",
  },
  {
    id: "SL-12903",
    name: "Sustain Hub Delta",
    location: "Austin, TX",
    owner: "Sarah Jenkins",
    status: "locked",
    role: "Nhà hàng",
    province: "Texas",
    totalDishes: 210,
    annualRevenue: "2.1 tỷ VND",
    ownerEmail: "sarah.jenkins@email.com",
    ownerPhone: "(512) 555-0789",
    ownerAddress: "101 Delta Blvd, Austin, TX 78701",
    createdAt: "03/11/2022",
  },
];